<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SSCPLUSL030" failures="1" tests="1" name="com.qa.houpermitproject.tests.RequestInformationTest" time="27.912" errors="0" timestamp="2023-07-25T10:25:14 CDT" skipped="0">
  <testcase classname="com.qa.houpermitproject.tests.RequestInformationTest" name="requestInformationUpdate" time="27.912">
    <failure message="The following asserts failed:
	expected [Please Provide an Update] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Please Provide an Update] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.qa.houpermitproject.tests.RequestInformationTest.requestInformationUpdate(RequestInformationTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[<a href='C:\Users\Taylor Bullard\Desktop\COH Project\Repo Files\HouPerPro_CreateProjectandRepo\HouPerProRegr\target\surefire-reports\failure_screenshots\requestInformationUpdate_25_07_2023_10_25_11.png'> <img src='C:\Users\Taylor Bullard\Desktop\COH Project\Repo Files\HouPerPro_CreateProjectandRepo\HouPerProRegr\target\surefire-reports\failure_screenshots\requestInformationUpdate_25_07_2023_10_25_11.png' height='100' width='100'/> </a>]]>
    </system-out>
  </testcase> <!-- requestInformationUpdate -->
  <system-out>
    <![CDATA[<a href='C:\Users\Taylor Bullard\Desktop\COH Project\Repo Files\HouPerPro_CreateProjectandRepo\HouPerProRegr\target\surefire-reports\failure_screenshots\requestInformationUpdate_25_07_2023_10_25_11.png'> <img src='C:\Users\Taylor Bullard\Desktop\COH Project\Repo Files\HouPerPro_CreateProjectandRepo\HouPerProRegr\target\surefire-reports\failure_screenshots\requestInformationUpdate_25_07_2023_10_25_11.png' height='100' width='100'/> </a>]]>
  </system-out>
</testsuite> <!-- com.qa.houpermitproject.tests.RequestInformationTest -->
